namespace: jstojanowski
name: devlab
version: 0.0.1
readme: README.md
authors:
  - Jarek Stojanowski JaSt <jstojanowski@gmail.com>
description: Ansible collection of roles for quick deploying development and DevOps environment.
license:
  - MIT
license_file: ''
tags:
  - infrastructure
  - linux
  - cloud
  - networking
  - devops
  - iac
  - homelab
  - cluster
  - terraform
  - toolset
  - server
  - zerotier
  - vpn
  - lxd
# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies: {}
repository: https://github.com/JaStDL/ansible_collection_devlab
documentation: https://github.com/JaStDL/ansible_collection_devlab
homepage: https://github.com/JaStDL/ansible_collection_devlab# The URL to the collection issue tracker
issues: https://github.com/JaStDL/ansible_collection_devlab/issues
build_ignore: []

# A dict controlling use of manifest directives used in building the collection artifact. The key 'directives' is a
# list of MANIFEST.in style
# L(directives,https://packaging.python.org/en/latest/guides/using-manifest-in/#manifest-in-commands). The key
# 'omit_default_directives' is a boolean that controls whether the default directives are used. Mutually exclusive
# with 'build_ignore'
# manifest: null
